#--------------------------------------------------------------
# $Id$
# History:
# 2025-03-05 - Imported from Action template & old .travis.yml  file
name: Build & test ccache

#---- Trigers -------------------------------------------------
on:
  push:
    branches: [ "windows", "master" ]
  pull_request:
    branches: [ "windows", "master" ]

#---- What to do ? --------------------------------------------
jobs:
  example_matrix:
    strategy:
      fail-fast: true
      matrix:
        # See existing oe from: https://github.com/actions/runner-images
        os: [ubuntu-20.04, ubuntu-latest]
        experimental: [false]
        include:
        - os: windows-2022
          experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: autogen
      run:  bash autogen.sh
    - name: configure 
      run:  bash configure $HOST
    - name: make
      run:  make
    - name: test
      run:  make ${TEST:-test}
