#--------------------------------------------------------------
# $Id$
# History:
# 2025-03-05 - Imported from Action template & old .travis.yml  file
name: Build & test ccache

#---- Trigers -------------------------------------------------
on:
  push:
    branches: [ "windows", "master" ]
  pull_request:
    branches: [ "windows", "master" ]

#---- What to do ? --------------------------------------------
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: configure
      run: ./autogen.sh && ./configure $HOST
    - name: make
      run:  make
    - name: test
      run:  make ${TEST:-test}
