#-----------------------------------------------------------------------------
# $Id: build-and-test.yml,v f9e6ba10d6da 2025/03/07 08:46:54 jdg $
# History:
# 2025-03-05 - Imported from Action template & old .travis.yml  file
name: Build & test ccache

#---- Trigers ----------------------------------------------------------------
on:
  push:
    branches: [ "windows", "master" ]
  pull_request:
    branches: [ "windows", "master" ]

#---- What to do ? -----------------------------------------------------------
jobs:
  example_matrix:
    #---- Defines variants of the compilation environments -------------------
    strategy:
      fail-fast: true
      matrix:
        # See existing oe from: https://github.com/actions/runner-images
        os: [ubuntu-20.04, ubuntu-latest]
        experimental: [false]
        include:
        - os: windows-2022
          experimental: true
          onWindows: true
          make: nmake

    #---- Run on the variants ------------------------------------------------
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
    - uses: actions/checkout@v4

    - name: Linux autogen and configure
      if:   ${{ ! matrix.onWindows }}
      run:  bash autogen.sh
      run:  bash configure $HOST

    - name: Windows configure ... not yet there !
      if:   ${{ matrix.onWindows }}
      run:  set
      run:  dir %CONDA%
      run:  dir %VCPKG_INSTALLATION_ROOT%
      run:  echo nmake > make.bat

    - name: make
      run:  make 

    - name: test
      run:  make ${TEST:-test}
